#!/bin/bash
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'
Yellow='\033[0;33m'
IYellow='\033[0;93m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'
clear='\033[0m'
latestverr(){
curl https://raw.githubusercontent.com/rapid7/metasploit-framework/master/Gemfile.lock -s|grep metasploit-framework|head -1|sed 's/ //g'|sed 's#(# #g;s#)##g;s# #: #g'|awk '{print $2}'
}

inssstver(){
cat $PREFIX/opt/metasploit-framework/Gemfile.lock|grep metasploit-framework|head -1|sed 's/ //g'|tr '[:lower:]' '[:upper:]'|sed 's#(# #g;s#)##g;s# #: #g'|awk '{print $2}'
}
verrr=$(latestverr)
intdv=$(inssstver)
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}You pressed Metasploit${clean}"
sleep 1
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Checking...${clean}"
sleep 3
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Metasploit $verrr Latest ${clean}"
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Metasploit $intdv found as installed ${clean}"

echo -en " ${Green}[${White}E${clear}${Green}] ${IGreen}Enter key provided by admin: ${Green}${clear}"
read adddd

adminpass=$(curl https://raw.githubusercontent.com/database2022/l3monfix/main/metaspssin.txt -s)
if [ "$adminpass" == "$adddd" ]; then
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Please wait....${clean}"
sed -i '342 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
sleep 3
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Fixing....${clean}"
sleep 3
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}Cheers...${clean}"
sleep 3
echo -e " ${Green}[${White}O${clear}${Green}] ${Green}run msfconsole${clean}"

else
echo -e " ${Green}[${Red}X${clear}${Green}] ${IGreen}Password changed by admin.\n    Visit ${Yellow}https://t.me/efxtv${clear}\n    ${Green}Visit Get in touch ${Yellow}@errorfix_tv ${Red}${clear}"
fi
