#!/bin/bash

Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'

ttsc()
{
ttscop=$(which pkg|grep -o "termux")
if [[ $ttscop == "termux" ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Termux found..${clear}"
else
echo -e "${Green}[${Red}Laddu${Green}]${Red} This script will work on termux only..${clear}"
echo -e "${Green}[${Red}Laddu${Green}]${Red} Thank you..${clear}"
exit
fi
}

checkunp()
{
whomd=$(whoami)
var="u0_a287 u0_a260 u0_a437 u0_a330 u0_a386 u0_a197 u0_a260 u0_a255 u0_a284 u0_a602 u0_a131"
dns=$(echo -e $var|grep -e "$whomd")
fse=$(echo -e $dns|grep -o "$whomd")


if [[ $whomd == $fse ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Checking device...${clear}"
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Paid user found...${clear}"
else
echo -e "${Green}[${Red}Laddu${Green}]${Red} Not a valid device.${clear}"
echo -e "${Green}[${Red}Laddu${Green}]${Red} Visit ${IGreen}t.me/efxtv ${Red}Thank you..${clear}"
exit
fi
}

checklmn()
{
if [[ -e $HOME/ubuntu22-fs/root/L3MON/maindb.json ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}L3MON setup found..${clear}"
else
echo -e "${Green}[${Red}ok${Green}]${Red} Correct L3MON path first..${clear}"
exit
fi
}



apks()
{
apkt=$(apktool -version|grep -o "2.7.1-SNAPSHOT")
if [[ $apkt == "2.7.1-SNAPSHOT" ]]; then
sleep 1
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Apktool found..${clear}"
else
echo -e "${Green}[${Red}ok${Green}]${Red} Install apktool first..${clear}"
exit
fi
}

javas()
{
apkt=$(apktool -version|grep -o "17-internal")
if [[ $apkt == "17-internal" ]]; then
sleep 1
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Java 17-internal found..${clear}"
else
echo -e "${Green}[${Red}ok${Green}]${Red} Install Java17 first..${clear}"
exit
fi
}

fixx()
{
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Fixing L3MON...${clear}"
apktool b $HOME/ubuntu22-fs/root/L3MON/app/factory/decompiled -o baba.apk > /dev/null 2>&1 ; rm baba.apk > /dev/null 2>&1
sleep 3
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Done...${clear}"
}

login()
{
echo -e "${Green}[${IGreen}ok${Green}] Server Started: ${IGreen}http://127.0.0.1:22533${clear}"
}
ttsc
checkunp
apks
javas
checklmn
fixx
login
