#!/bin/bash

Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'

checkunp()
{
unst=$(whoami)
if [[ $unst == "u0_a284" ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Checking device...${clear}"
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Paid user found...${clear}"
else
echo -e "${Green}[${Red}Laddu${Green}]${Red} Not a valid device.${clear}"
echo -e "${Green}[${Red}Laddu${Green}]${Red} Visit ${IGreen}t.me/efxtv ${Red}Thank you..${clear}"
exit
fi
}

checklmn()
{
if [[ -e $HOME/ubuntu22-fs/root/L3MON/maindb.json ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}L3MON setup found..${clear}"
else
echo -e "${Green}[${Red}ok${Green}]${Red} Correct L3MON path first..${clear}"
exit
fi
}

ttsc()
{
ttscop=$(which pkg|grep -o "termux")
if [[ $ttscop == "termux" ]]; then
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Termux found..${clear}"
else
echo -e "${Green}[${Red}Laddu${Green}]${Red} This script will work on termux only..${clear}"
echo -e "${Green}[${Red}Laddu${Green}]${Red} Thank you..${clear}"
exit
fi
}

apks()
{
apkt=$(which apktool|grep -o "apktool")
if [[ $apkt == "apktool" ]]; then
sleep 1
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Apktool found..${clear}"
else
echo -e "${Green}[${Red}ok${Green}]${Red} Install apktool first..${clear}"
fi
}

fixx()
{
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Fixing L3MON...${clear}"
apktool b $HOME/ubuntu22-fs/root/L3MON/app/factory/decompiled -o baba.apk > /dev/null 2>&1 ; rm baba.apk > /dev/null 2>&1
sleep 3
echo -e "${Green}[${IGreen}ok${Green}] ${IGreen}Done...${clear}"
}

login()
{
echo -e "${Green}[${IGreen}ok${Green}] Server Started: ${IGreen}http://127.0.0.1:22533${clear}"
}
checkunp
ttsc
checklmn
apks
fixx
login
